source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

project 'CPEExperienceExampleCocoapods'
workspace 'CPEExperienceExampleWorkspaceCocoaPods'

target 'CPEExperienceExample' do
    
    use_frameworks!
    
    pod 'CPEData',          '~> 3.0'
    pod 'CPEExperience',    :path => '../'

end