source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

project 'CPEExperienceExample'
workspace 'CPEExperienceExampleWorkspace'

target 'CPEExperienceExample' do
    use_modular_headers!
    
    pod 'CPEData',          '~> 3.2'
    pod 'CPEExperience',    :path => '../'

end